### ISSUE TITLE
Arduino Code Not Counting First Incorrectly Pressed Button

### ISSUE THREAD

**Issue by ammrat13** [ncgadgetry/southeastcon2020#1]
I was put in charge of simulating the button pushing code for Georgia Tech's IEEE Robotics Team, and while doing so, I think I uncovered a bug. I essentially did my best to copy your `ArduinoControl.ino` file as closely as possible. I noticed that, when testing to make sure incorrect presses are scored correctly (which I did by pressing `0` a thousand times), I recieved a score one lower than expected. I recieved a score of `999` instead of `1000`.

I traced through both my and your code and found the relevant source lines in my code to be `simulator/Buttons.py` lines `271` to `285`, which correspond to `ArduinoControl.ino` lines `257` to `298`. It seems that on the first incorrect press (`inSequence == true` and `newPress == true` and `buttonState[digit].buttonState == false`), your code correctly sets `numSequenced` to `piDigitPosn` but forgets to increment `extraNotPressed`.  

The code is available on our repository: [GT-IEEE-Robotics/Simulator2020](https://github.com/GT-IEEE-Robotics/Simulator2020) commit `7a4a020` if you'd like to check this.

**Comment by ncgadgetry** [comment]
Thank you for a valid bug report and code analysis. I will update the code to reflect your bug report in a few days and give you credit for the bug.

Thanx!

**Comment by ncgadgetry** [comment]
Issue resolved in latest push - thanx!

I also added your name to the list of contributors for the code!
