### ISSUE TITLE
Arduino Mega 2560 running out of dynamic memory when using ArenaControl code

### ISSUE THREAD

**Issue by mdixson2** [ncgadgetry/southeastcon2020#2]
I have downloaded the git repo as a zip file. I opened the ArenaControl code using the Arduino 1.8.10 IDE. When uploading it to a Mega 2560 Arduino, an error occurs. It states:

"Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega    2560)
Sketch uses 13930 bytes (5%) of program storage space. Maximum is 253952 bytes.
Global variables use 10284 bytes (125%) of dynamic memory, leaving -2092 bytes for local variables. Maximum is 8192 bytes.
Not enough memory;
Error compiling for board Arduino/Genuino Mega or Mega 2560."

Is there a fix for this issue?

**Comment by mdixson2** [comment]
Thank you. That works

**Comment by mlaga97** [comment]
You'll likely want to keep the issue open until the issue has been resolved on the master branch.
